#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Quilmes")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTabla_Usuario(Tabla_Usuario instance);
    partial void UpdateTabla_Usuario(Tabla_Usuario instance);
    partial void DeleteTabla_Usuario(Tabla_Usuario instance);
    partial void InsertTabla_CodigoTapa(Tabla_CodigoTapa instance);
    partial void UpdateTabla_CodigoTapa(Tabla_CodigoTapa instance);
    partial void DeleteTabla_CodigoTapa(Tabla_CodigoTapa instance);
    partial void InsertTabla_Sugerencias(Tabla_Sugerencias instance);
    partial void UpdateTabla_Sugerencias(Tabla_Sugerencias instance);
    partial void DeleteTabla_Sugerencias(Tabla_Sugerencias instance);
    partial void InsertTabla_TipoMusica(Tabla_TipoMusica instance);
    partial void UpdateTabla_TipoMusica(Tabla_TipoMusica instance);
    partial void DeleteTabla_TipoMusica(Tabla_TipoMusica instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuilmesConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tabla_Usuario> Tabla_Usuario
		{
			get
			{
				return this.GetTable<Tabla_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_CodigoTapa> Tabla_CodigoTapa
		{
			get
			{
				return this.GetTable<Tabla_CodigoTapa>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_Sugerencias> Tabla_Sugerencias
		{
			get
			{
				return this.GetTable<Tabla_Sugerencias>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_TipoMusica> Tabla_TipoMusica
		{
			get
			{
				return this.GetTable<Tabla_TipoMusica>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.datosDelUsuario")]
		public int datosDelUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,10)")] System.Nullable<decimal> latitudUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,10)")] System.Nullable<decimal> longitudUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string ipAddres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string loteCerveza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), latitudUsuario, longitudUsuario, ipAddres, loteCerveza);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LogueoUsuario")]
		public int LogueoUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoTapa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> respuesta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoTapa, respuesta);
			respuesta = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sugerenciaDelUsuario")]
		public int sugerenciaDelUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string mensajeSugerencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mensajeSugerencia, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_Usuario")]
	public partial class Tabla_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Usuario;
		
		private System.Nullable<decimal> _latitudUsuario;
		
		private System.Nullable<decimal> _longitudUsuario;
		
		private string _ipAddress;
		
		private string _loteCerveza;
		
		private System.Nullable<System.DateTime> _fechaToma;
		
		private EntitySet<Tabla_Sugerencias> _Tabla_Sugerencias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_UsuarioChanging(int value);
    partial void Onid_UsuarioChanged();
    partial void OnlatitudUsuarioChanging(System.Nullable<decimal> value);
    partial void OnlatitudUsuarioChanged();
    partial void OnlongitudUsuarioChanging(System.Nullable<decimal> value);
    partial void OnlongitudUsuarioChanged();
    partial void OnipAddressChanging(string value);
    partial void OnipAddressChanged();
    partial void OnloteCervezaChanging(string value);
    partial void OnloteCervezaChanged();
    partial void OnfechaTomaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaTomaChanged();
    #endregion
		
		public Tabla_Usuario()
		{
			this._Tabla_Sugerencias = new EntitySet<Tabla_Sugerencias>(new Action<Tabla_Sugerencias>(this.attach_Tabla_Sugerencias), new Action<Tabla_Sugerencias>(this.detach_Tabla_Sugerencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					this.Onid_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._id_Usuario = value;
					this.SendPropertyChanged("id_Usuario");
					this.Onid_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitudUsuario", DbType="Decimal(18,10)")]
		public System.Nullable<decimal> latitudUsuario
		{
			get
			{
				return this._latitudUsuario;
			}
			set
			{
				if ((this._latitudUsuario != value))
				{
					this.OnlatitudUsuarioChanging(value);
					this.SendPropertyChanging();
					this._latitudUsuario = value;
					this.SendPropertyChanged("latitudUsuario");
					this.OnlatitudUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitudUsuario", DbType="Decimal(18,10)")]
		public System.Nullable<decimal> longitudUsuario
		{
			get
			{
				return this._longitudUsuario;
			}
			set
			{
				if ((this._longitudUsuario != value))
				{
					this.OnlongitudUsuarioChanging(value);
					this.SendPropertyChanging();
					this._longitudUsuario = value;
					this.SendPropertyChanged("longitudUsuario");
					this.OnlongitudUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipAddress", DbType="NVarChar(30)")]
		public string ipAddress
		{
			get
			{
				return this._ipAddress;
			}
			set
			{
				if ((this._ipAddress != value))
				{
					this.OnipAddressChanging(value);
					this.SendPropertyChanging();
					this._ipAddress = value;
					this.SendPropertyChanged("ipAddress");
					this.OnipAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loteCerveza", DbType="NVarChar(50)")]
		public string loteCerveza
		{
			get
			{
				return this._loteCerveza;
			}
			set
			{
				if ((this._loteCerveza != value))
				{
					this.OnloteCervezaChanging(value);
					this.SendPropertyChanging();
					this._loteCerveza = value;
					this.SendPropertyChanged("loteCerveza");
					this.OnloteCervezaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaToma", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaToma
		{
			get
			{
				return this._fechaToma;
			}
			set
			{
				if ((this._fechaToma != value))
				{
					this.OnfechaTomaChanging(value);
					this.SendPropertyChanging();
					this._fechaToma = value;
					this.SendPropertyChanged("fechaToma");
					this.OnfechaTomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabla_Usuario_Tabla_Sugerencias", Storage="_Tabla_Sugerencias", ThisKey="id_Usuario", OtherKey="id_Usuario")]
		public EntitySet<Tabla_Sugerencias> Tabla_Sugerencias
		{
			get
			{
				return this._Tabla_Sugerencias;
			}
			set
			{
				this._Tabla_Sugerencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabla_Sugerencias(Tabla_Sugerencias entity)
		{
			this.SendPropertyChanging();
			entity.Tabla_Usuario = this;
		}
		
		private void detach_Tabla_Sugerencias(Tabla_Sugerencias entity)
		{
			this.SendPropertyChanging();
			entity.Tabla_Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_CodigoTapa")]
	public partial class Tabla_CodigoTapa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_CodigoTapa;
		
		private System.Nullable<int> _codigoTapa;
		
		private string _ubicacionMusica;
		
		private System.Nullable<bool> _codigoUtilizado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_CodigoTapaChanging(int value);
    partial void Onid_CodigoTapaChanged();
    partial void OncodigoTapaChanging(System.Nullable<int> value);
    partial void OncodigoTapaChanged();
    partial void OnubicacionMusicaChanging(string value);
    partial void OnubicacionMusicaChanged();
    partial void OncodigoUtilizadoChanging(System.Nullable<bool> value);
    partial void OncodigoUtilizadoChanged();
    #endregion
		
		public Tabla_CodigoTapa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_CodigoTapa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_CodigoTapa
		{
			get
			{
				return this._id_CodigoTapa;
			}
			set
			{
				if ((this._id_CodigoTapa != value))
				{
					this.Onid_CodigoTapaChanging(value);
					this.SendPropertyChanging();
					this._id_CodigoTapa = value;
					this.SendPropertyChanged("id_CodigoTapa");
					this.Onid_CodigoTapaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoTapa", DbType="Int")]
		public System.Nullable<int> codigoTapa
		{
			get
			{
				return this._codigoTapa;
			}
			set
			{
				if ((this._codigoTapa != value))
				{
					this.OncodigoTapaChanging(value);
					this.SendPropertyChanging();
					this._codigoTapa = value;
					this.SendPropertyChanged("codigoTapa");
					this.OncodigoTapaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacionMusica", DbType="NVarChar(50)")]
		public string ubicacionMusica
		{
			get
			{
				return this._ubicacionMusica;
			}
			set
			{
				if ((this._ubicacionMusica != value))
				{
					this.OnubicacionMusicaChanging(value);
					this.SendPropertyChanging();
					this._ubicacionMusica = value;
					this.SendPropertyChanged("ubicacionMusica");
					this.OnubicacionMusicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoUtilizado", DbType="Bit")]
		public System.Nullable<bool> codigoUtilizado
		{
			get
			{
				return this._codigoUtilizado;
			}
			set
			{
				if ((this._codigoUtilizado != value))
				{
					this.OncodigoUtilizadoChanging(value);
					this.SendPropertyChanging();
					this._codigoUtilizado = value;
					this.SendPropertyChanged("codigoUtilizado");
					this.OncodigoUtilizadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_Sugerencias")]
	public partial class Tabla_Sugerencias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Mensaje;
		
		private System.Nullable<int> _id_Usuario;
		
		private string _mensajeSugerencia;
		
		private EntityRef<Tabla_Usuario> _Tabla_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_MensajeChanging(int value);
    partial void Onid_MensajeChanged();
    partial void Onid_UsuarioChanging(System.Nullable<int> value);
    partial void Onid_UsuarioChanged();
    partial void OnmensajeSugerenciaChanging(string value);
    partial void OnmensajeSugerenciaChanged();
    #endregion
		
		public Tabla_Sugerencias()
		{
			this._Tabla_Usuario = default(EntityRef<Tabla_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Mensaje", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Mensaje
		{
			get
			{
				return this._id_Mensaje;
			}
			set
			{
				if ((this._id_Mensaje != value))
				{
					this.Onid_MensajeChanging(value);
					this.SendPropertyChanging();
					this._id_Mensaje = value;
					this.SendPropertyChanged("id_Mensaje");
					this.Onid_MensajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Usuario", DbType="Int")]
		public System.Nullable<int> id_Usuario
		{
			get
			{
				return this._id_Usuario;
			}
			set
			{
				if ((this._id_Usuario != value))
				{
					if (this._Tabla_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._id_Usuario = value;
					this.SendPropertyChanged("id_Usuario");
					this.Onid_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mensajeSugerencia", DbType="NVarChar(MAX)")]
		public string mensajeSugerencia
		{
			get
			{
				return this._mensajeSugerencia;
			}
			set
			{
				if ((this._mensajeSugerencia != value))
				{
					this.OnmensajeSugerenciaChanging(value);
					this.SendPropertyChanging();
					this._mensajeSugerencia = value;
					this.SendPropertyChanged("mensajeSugerencia");
					this.OnmensajeSugerenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabla_Usuario_Tabla_Sugerencias", Storage="_Tabla_Usuario", ThisKey="id_Usuario", OtherKey="id_Usuario", IsForeignKey=true, DeleteRule="CASCADE")]
		public Tabla_Usuario Tabla_Usuario
		{
			get
			{
				return this._Tabla_Usuario.Entity;
			}
			set
			{
				Tabla_Usuario previousValue = this._Tabla_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Tabla_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tabla_Usuario.Entity = null;
						previousValue.Tabla_Sugerencias.Remove(this);
					}
					this._Tabla_Usuario.Entity = value;
					if ((value != null))
					{
						value.Tabla_Sugerencias.Add(this);
						this._id_Usuario = value.id_Usuario;
					}
					else
					{
						this._id_Usuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tabla_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_TipoMusica")]
	public partial class Tabla_TipoMusica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_TipoMusica;
		
		private string _TipoMusica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_TipoMusicaChanging(int value);
    partial void Onid_TipoMusicaChanged();
    partial void OnTipoMusicaChanging(string value);
    partial void OnTipoMusicaChanged();
    #endregion
		
		public Tabla_TipoMusica()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_TipoMusica", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_TipoMusica
		{
			get
			{
				return this._id_TipoMusica;
			}
			set
			{
				if ((this._id_TipoMusica != value))
				{
					this.Onid_TipoMusicaChanging(value);
					this.SendPropertyChanging();
					this._id_TipoMusica = value;
					this.SendPropertyChanged("id_TipoMusica");
					this.Onid_TipoMusicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoMusica", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TipoMusica
		{
			get
			{
				return this._TipoMusica;
			}
			set
			{
				if ((this._TipoMusica != value))
				{
					this.OnTipoMusicaChanging(value);
					this.SendPropertyChanging();
					this._TipoMusica = value;
					this.SendPropertyChanged("TipoMusica");
					this.OnTipoMusicaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
